@PORT={{$dotenv PORT}}
@BASE_URL=http://localhost:{{PORT}}
@USERNAME={{$dotenv USERNAME}}
@PASSWORD={{$dotenv PASSWORD}}
@TOKEN=bearer {{login.response.body.token}}
login.response.headers.Set-Cookie


###
# Health check (SANITY CHECK)
GET {{BASE_URL}}/api/health

###
# Logout
DELETE {{BASE_URL}}/api/logout


###
# @name login
# Login
POST {{BASE_URL}}/api/login
Content-Type: application/json

{
  "username": "{{USERNAME}}",
  "password": "{{PASSWORD}}"
}