@PORT={{$dotenv PORT}}
@BASE_URL=http://localhost:{{PORT}}
@ID=10
@USERNAME=Created_User_Name

###
# Health check (SANITY CHECK)
GET {{BASE_URL}}/api/health

###
# Get all users
GET {{BASE_URL}}/api/users/


###
# Returns the users entire reading list 
GET {{BASE_URL}}/api/users/1

###
# Returns the users blogs that have been read 
GET {{BASE_URL}}/api/users/1?read=true


###
# Create New User
POST {{BASE_URL}}/api/users
Content-Type: application/json
# password hash is sekret

{
  "name": "Root User",
  "username": "rootUser@gmail.com",
  "password": "sekret"
}

###
# Create New User with incorrect username
POST {{BASE_URL}}/api/users
Content-Type: application/json
# password hash is sekret

{
  "name": "Created User",
  "username": "Created_User_Name",
  "hashedPassword": "sekret"
}

###
# Get a user by username
PUT {{BASE_URL}}/api/users/{{USERNAME}}
Content-Type: application/json

{
  "username": "Created_User_Name@gmail.com"
}
