version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./commands.sql:/docker-entrypoint-initdb.d/init.sql

      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  app-backend:
    image: bloglist-backend
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - 3005:3005
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
    container_name: bloglist-backend
  