version: '3.8'

services:

  db:
    container_name: db-1
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USERNAME: postgres
    volumes:
      - ./postgres-data/init.sql:/docker-entrypoint-initdb.d/init.sql

      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  app-backend:
    depends_on:
      - db
    image: bloglist-backend
    restart: always
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - 3005:3005
    env_file: 
      - .env
      # The volumes line must be included in the dev environment or nodemon will not work correctly
    volumes:
      - ./:/usr/src/app
    container_name: bloglist-backend
  